version: "3.6"

services:
    whoami:
        image: traefik/whoami:v1.6.0
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - traefik.enable=true
                - traefik.docker.network=lb_network
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.whoami.rule=Path(`/whoami`)
                - traefik.http.services.whoami.loadbalancer.server.port=80
        networks:
            - lb_network


    traefik:
        image: traefik:v2.3.1
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: tcp
              mode: host      
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                max_attempts: 3
                window: 120s
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        command:
            - --providers.docker
            - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
            - --providers.docker.exposedbydefault=false
            - --providers.docker.swarmmode
            - --entrypoints.http.address=:80
            - --entrypoints.https.address=:443
            #- --log.level=INFO
            - --accesslog
            - --log
            - --api
        networks:
            - lb_network

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  lb_network:
